[package]
name = "isolang"
version = "0.1.0"
edition = "2024"


[dependencies.clap]
version  = "4.5"
features = [ "derive" ]

[dependencies.rand]
version = "0.9"


[lints.rust]
unused_parens = "allow"
missing_docs  = "deny"

[lints.clippy]
missing_docs_in_private_items = "deny"
